# Generated by Django 5.2.8 on 2025-11-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title for your blog post.', max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sub_title', models.CharField(blank=True, help_text='Enter a sub-title for your blog post.', max_length=100)),
                ('content', models.TextField(help_text='Enter the content of your blog post here.', max_length=2000, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time at which your post was created.')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The last time your blog post was updated.')),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
    ]
