# Generated by Django 5.2.8 on 2025-11-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Enter the content of your blog post here.', max_length=10000, unique=True),
        ),
    ]
