# Generated by Django 5.2.8 on 2025-11-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Enter the content of your blog post here.', max_length=100000, unique=True),
        ),
    ]
